name = "execution-tracker"
main = "worker.js"
compatibility_date = "2025-01-01"

[[durable_objects.bindings]]
name = "TRACKER"
class_name = "TrackerDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TrackerDO"]

[triggers]
crons = ["* * * * *"]
